[vps]
vps-monitoring ansible_host=217.197.115.100

[vps:vars]
vault_port=8200

[localhost]
127.0.0.1 ansible_connection=local

[localhost:vars]
oracle_db_host=172.25.15.3
oracle_db_port=1521
oracle_db_service_name=MAKC
