---
- name: Deploying/updating monitoring infrastructure on VPS
  hosts: vps
  gather_facts: false
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: "~/.ssh/MadMax2Quasar_ed"
    project_dir: "/home/ansible/github_projects/oracle-db-monitoring-ecosystem"
    repo_url: "https://github.com/argoflux-dev/oracle-db-monitoring-ecosystem"

  tasks:
    - name: 1. Loading encrypted variables
      include_vars:
        file: credentials.yml
        name: vault_secrets

    - name: 2. Setting variables from vault_secrets
      set_fact:
        vault_root_token: "{{ vault_secrets.vault_root_token }}"
        vault_port: "{{ vault_secrets.vault_port | default(8200) }}"
        db_username: "{{ vault_secrets.db_username }}"
        db_password: "{{ vault_secrets.db_password }}"
        oracle_db_host: "{{ vault_secrets.oracle_db_host }}"
        oracle_db_port: "{{ vault_secrets.oracle_db_port }}"
        oracle_db_service_name: "{{ vault_secrets.oracle_db_service_name }}"

    - name: 3. Creating a directory for projects
      file:
        path: "/home/ansible/github_projects"
        state: directory
        owner: ansible
        group: ansible
        mode: '0755'

    - name: 4. Cloning or updating a repository from GitHub
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        version: main
        force: yes

    - name: 5. Generating prometheus.yml and alert rules files
      template:
        src: "{{ item.src }}"
        dest: "{{ project_dir }}/infra-telemetry/prometheus/{{ item.dest }}"
        owner: ansible
        group: ansible
        mode: '0644'
      loop:
        - { src: 'prometheus.yml.j2', dest: 'prometheus.yml' }
        - { src: 'alert_rules.yml.j2', dest: 'alert_rules.yml' }

    - name: 6. Generating the alertmanager.yml configuration file (with secrets from Ansible Vault inserted)
      template:
        src: alertmanager.yml.j2
        dest: "{{ project_dir }}/infra-telemetry/alertmanager/alertmanager.yml"
        owner: ansible
        group: ansible
        mode: '0644'

    - name: 7. Running containers with Docker Compose
      command:
        cmd: docker compose up -d --force-recreate
        chdir: "{{ project_dir }}/infra-telemetry/"
      environment:
        VAULT_DEV_ROOT_TOKEN: "{{ vault_root_token }}"

    - name: 8. Waiting for Vault API to start
      wait_for:
        port: "{{ vault_port }}"
        delay: 3
        timeout: 30

    - name: 9. Creating Secrets for Oracle DB in Vault
      uri:
        url: "http://localhost:{{ vault_port }}/v1/secret/data/oracle"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_root_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          data:
            username: "{{ db_username }}"
            password: "{{ db_password }}"
            dsn: "{{ oracle_db_host }}:{{ oracle_db_port }}/{{ oracle_db_service_name }}"
        status_code: [200, 204]
